# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payment_estimate_fee_request import PaymentEstimateFeeRequest


class TestPaymentEstimateFeeRequest(unittest.TestCase):
    """PaymentEstimateFeeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentEstimateFeeRequest:
        """Test PaymentEstimateFeeRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentEstimateFeeRequest`
        """
        model = PaymentEstimateFeeRequest()
        if include_optional:
            return PaymentEstimateFeeRequest(
                fee_type = 'Order',
                estimate_fees = [
                    cobo_waas2.models.payment_estimate_fee.PaymentEstimateFee(
                        token_id = '', 
                        amount = '500.00', )
                    ],
                recipient_token_id = '',
                transfer_via_va = False
            )
        else:
            return PaymentEstimateFeeRequest(
                estimate_fees = [
                    cobo_waas2.models.payment_estimate_fee.PaymentEstimateFee(
                        token_id = '', 
                        amount = '500.00', )
                    ],
        )
        """

    def testPaymentEstimateFeeRequest(self):
        """Test PaymentEstimateFeeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
