# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payment_payout_event import PaymentPayoutEvent


class TestPaymentPayoutEvent(unittest.TestCase):
    """PaymentPayoutEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentPayoutEvent:
        """Test PaymentPayoutEvent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentPayoutEvent`
        """
        model = PaymentPayoutEvent()
        if include_optional:
            return PaymentPayoutEvent(
                data_type = 'Transaction',
                payout_id = '123e457-e89b-12d3-a456-426614174004',
                request_id = '123e457-e89b-12d3-a456-426614174004',
                payout_channel = 'Crypto',
                source_account = '',
                payout_items = [
                    cobo_waas2.models.payment_payout_item.PaymentPayoutItem(
                        token_id = 'ETH_USDT', 
                        amount = '500.00', 
                        bridging_fee = cobo_waas2.models.bridging_fee.BridgingFee(
                            fee_amount = '', 
                            received_token_id = '', 
                            received_amount = '', 
                            bridge_status = 'Completed', ), )
                    ],
                recipient_info = cobo_waas2.models.payment_payout_recipient_info.PaymentPayoutRecipientInfo(
                    address = '0x9876543210abcdef1234567890abcdef12345678', 
                    token_id = 'TRON_USDT', 
                    currency = 'USD', 
                    bank_account_id = '123e4567-e89b-12d3-a456-426614174003', 
                    transfer_via_va = False, ),
                initiator = 'b2ae1b5aaade686c968ef2bbd31cc75ba94e5a85fd9cb0b35b81dcc15f520e9d',
                actual_payout_amount = '500.00',
                commission_fees = [
                    cobo_waas2.models.commission_fee.CommissionFee(
                        fee_amount = '', )
                    ],
                remark = 'Payout for customer 123',
                status = 'Pending',
                created_timestamp = 1744689600,
                updated_timestamp = 1744689600,
                transactions = [
                    cobo_waas2.models.payment_transaction.PaymentTransaction(
                        tx_id = 'tx_123e4567-e89b-12d3-a456-426614174003', 
                        tx_hash = '0x742d35Cc6634C0532925a3b844Bc454e4438f44e', 
                        token_id = 'ETH_USDT', 
                        from_address = '0xF8e4bfc10A2821DF52D3322cB5170E5E9276b537', 
                        to_address = '0x15B95A2D8af95D9F48148667B6b8B3CdF89e4F15', 
                        amount = '0.15', 
                        status = 'Submitted', 
                        counterparty = cobo_waas2.models.counterparty.Counterparty(
                            counterparty_id = '123e4567-e89b-12d3-a456-426614174003', 
                            counterparty_type = 'Individual', 
                            counterparty_name = 'Counterparty A', 
                            country = 'USA', 
                            email = 'counterparty@example.com', 
                            contact_address = '123 Main St, Anytown, USA', 
                            created_timestamp = 1744689600, 
                            updated_timestamp = 1744689600, ), 
                        destination = cobo_waas2.models.destination.Destination(
                            destination_id = '123e4567-e89b-12d3-a456-426614174003', 
                            destination_type = 'Individual', 
                            destination_name = 'Destination A', 
                            country = 'USA', 
                            email = 'destination@example.com', 
                            contact_address = '123 Main St, Anytown, USA', 
                            merchant_id = 'M1001', 
                            created_timestamp = 1744689600, 
                            updated_timestamp = 1744689600, ), 
                        created_timestamp = 1610445878970, 
                        updated_timestamp = 1610445878970, )
                    ]
            )
        else:
            return PaymentPayoutEvent(
                data_type = 'Transaction',
                payout_id = '123e457-e89b-12d3-a456-426614174004',
                request_id = '123e457-e89b-12d3-a456-426614174004',
                payout_channel = 'Crypto',
                status = 'Pending',
                created_timestamp = 1744689600,
                updated_timestamp = 1744689600,
        )
        """

    def testPaymentPayoutEvent(self):
        """Test PaymentPayoutEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
