# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_refund_link_request import CreateRefundLinkRequest


class TestCreateRefundLinkRequest(unittest.TestCase):
    """CreateRefundLinkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRefundLinkRequest:
        """Test CreateRefundLinkRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRefundLinkRequest`
        """
        model = CreateRefundLinkRequest()
        if include_optional:
            return CreateRefundLinkRequest(
                business_info = cobo_waas2.models.refund_link_business_info.RefundLinkBusinessInfo(
                    order_id = 'O20250304-M1001-1001', 
                    transaction_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f', 
                    amount = '0.0025', 
                    refund_source = 'Merchant', 
                    merchant_id = 'M1001', 
                    fee_amount = '0.0001', ),
                display_info = cobo_waas2.models.link_display_info.LinkDisplayInfo(
                    developer_name = 'Acme Payment Solutions', 
                    logo = 'https://example.com/logo.png', 
                    return_url = 'https://example.com/return', )
            )
        else:
            return CreateRefundLinkRequest(
                business_info = cobo_waas2.models.refund_link_business_info.RefundLinkBusinessInfo(
                    order_id = 'O20250304-M1001-1001', 
                    transaction_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f', 
                    amount = '0.0025', 
                    refund_source = 'Merchant', 
                    merchant_id = 'M1001', 
                    fee_amount = '0.0001', ),
        )
        """

    def testCreateRefundLinkRequest(self):
        """Test CreateRefundLinkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
