# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payment_payout import PaymentPayout


class TestPaymentPayout(unittest.TestCase):
    """PaymentPayout unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentPayout:
        """Test PaymentPayout
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentPayout`
        """
        model = PaymentPayout()
        if include_optional:
            return PaymentPayout(
                payout_id = '123e457-e89b-12d3-a456-426614174004',
                request_id = '123e457-e89b-12d3-a456-426614174004',
                payout_channel = 'Crypto',
                source_account = '',
                payout_items = [
                    cobo_waas2.models.payment_payout_item.PaymentPayoutItem(
                        token_id = 'ETH_USDT', 
                        amount = '500.00', 
                        bridging_fee = cobo_waas2.models.bridging_fee.BridgingFee(
                            fee_amount = '', 
                            received_token_id = '', 
                            received_amount = '', 
                            bridge_status = 'Completed', ), )
                    ],
                recipient_info = cobo_waas2.models.payment_payout_recipient_info.PaymentPayoutRecipientInfo(
                    address = '0x9876543210abcdef1234567890abcdef12345678', 
                    token_id = 'TRON_USDT', 
                    currency = 'USD', 
                    bank_account_id = '123e4567-e89b-12d3-a456-426614174003', 
                    transfer_via_va = False, ),
                initiator = 'b2ae1b5aaade686c968ef2bbd31cc75ba94e5a85fd9cb0b35b81dcc15f520e9d',
                actual_payout_amount = '500.00',
                commission_fees = [
                    cobo_waas2.models.commission_fee.CommissionFee(
                        fee_amount = '', )
                    ],
                remark = 'Payout for customer 123',
                status = 'Pending',
                created_timestamp = 1744689600,
                updated_timestamp = 1744689600
            )
        else:
            return PaymentPayout(
                payout_id = '123e457-e89b-12d3-a456-426614174004',
                request_id = '123e457-e89b-12d3-a456-426614174004',
                payout_channel = 'Crypto',
                status = 'Pending',
                created_timestamp = 1744689600,
                updated_timestamp = 1744689600,
        )
        """

    def testPaymentPayout(self):
        """Test PaymentPayout"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
