# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_payout_request import CreatePayoutRequest


class TestCreatePayoutRequest(unittest.TestCase):
    """CreatePayoutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePayoutRequest:
        """Test CreatePayoutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePayoutRequest`
        """
        model = CreatePayoutRequest()
        if include_optional:
            return CreatePayoutRequest(
                request_id = '123e457-e89b-12d3-a456-426614174004',
                source_account = '',
                payout_channel = 'Crypto',
                payout_params = [
                    cobo_waas2.models.payment_payout_param.PaymentPayoutParam(
                        token_id = 'ETH_USDT', 
                        amount = '500.00', )
                    ],
                recipient_info = cobo_waas2.models.payment_payout_recipient_info.PaymentPayoutRecipientInfo(
                    address = '0x9876543210abcdef1234567890abcdef12345678', 
                    token_id = 'TRON_USDT', 
                    currency = 'USD', 
                    bank_account_id = '123e4567-e89b-12d3-a456-426614174003', 
                    transfer_via_va = False, ),
                remark = 'Create payouts for customer 123'
            )
        else:
            return CreatePayoutRequest(
                request_id = '123e457-e89b-12d3-a456-426614174004',
                source_account = '',
                payout_channel = 'Crypto',
                payout_params = [
                    cobo_waas2.models.payment_payout_param.PaymentPayoutParam(
                        token_id = 'ETH_USDT', 
                        amount = '500.00', )
                    ],
                recipient_info = cobo_waas2.models.payment_payout_recipient_info.PaymentPayoutRecipientInfo(
                    address = '0x9876543210abcdef1234567890abcdef12345678', 
                    token_id = 'TRON_USDT', 
                    currency = 'USD', 
                    bank_account_id = '123e4567-e89b-12d3-a456-426614174003', 
                    transfer_via_va = False, ),
        )
        """

    def testCreatePayoutRequest(self):
        """Test CreatePayoutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
