# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_auto_sweep_task import CreateAutoSweepTask


class TestCreateAutoSweepTask(unittest.TestCase):
    """CreateAutoSweepTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAutoSweepTask:
        """Test CreateAutoSweepTask
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAutoSweepTask`
        """
        model = CreateAutoSweepTask()
        if include_optional:
            return CreateAutoSweepTask(
                wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                token_id = 'ETH_USDT',
                min_balance_threshold = '0.01'
            )
        else:
            return CreateAutoSweepTask(
                wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                token_id = 'ETH_USDT',
        )
        """

    def testCreateAutoSweepTask(self):
        """Test CreateAutoSweepTask"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
