# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2 import Configuration
from cobo_waas2.api.payment_api import PaymentApi


class TestPaymentApi(unittest.TestCase):
    """PaymentApi unit test stubs"""

    def setUp(self) -> None:
        Configuration.set_default(Configuration(
            api_private_key="c203fccc02a2269ec486d9c32ff74b5ba6ab0cdb461ee1fb0dfc616109115c06",
            host="https://api.sandbox.cobo.com/v2"
        ))
        self.api = PaymentApi()

    def tearDown(self) -> None:
        pass

    def test_batch_get_exchange_rates(self) -> None:
        """
        Test case for batch_get_exchange_rates

        Batch get exchange rates
        """
        """
        token_ids = 'ETH_USDT,ETH_USDC,BTC_USDT'
        currencies = 'USD'

        api_response = self.api.batch_get_exchange_rates(token_ids, currencies)
        """

    def test_cancel_refund_by_id(self) -> None:
        """
        Test case for cancel_refund_by_id

        Cancel refund order
        """
        """
        refund_id = 'R20250304-M1001-1001'

        api_response = self.api.cancel_refund_by_id(refund_id)
        """

    def test_create_batch_allocation(self) -> None:
        """
        Test case for create_batch_allocation

        Create batch allocation
        """
        """
        create_batch_allocation_request = cobo_waas2.CreateBatchAllocationRequest()

        api_response = self.api.create_batch_allocation(create_batch_allocation_request=create_batch_allocation_request)
        """

    def test_create_bulk_send(self) -> None:
        """
        Test case for create_bulk_send

        Create bulk send
        """
        """
        create_bulk_send_request = cobo_waas2.CreateBulkSendRequest()

        api_response = self.api.create_bulk_send(create_bulk_send_request=create_bulk_send_request)
        """

    def test_create_counterparty(self) -> None:
        """
        Test case for create_counterparty

        Create counterparty
        """
        """
        create_counterparty_request = cobo_waas2.CreateCounterpartyRequest()

        api_response = self.api.create_counterparty(create_counterparty_request=create_counterparty_request)
        """

    def test_create_counterparty_entry(self) -> None:
        """
        Test case for create_counterparty_entry

        Create counterparty entry
        """
        """
        create_counterparty_entry_request = cobo_waas2.CreateCounterpartyEntryRequest()

        api_response = self.api.create_counterparty_entry(create_counterparty_entry_request=create_counterparty_entry_request)
        """

    def test_create_crypto_address(self) -> None:
        """
        Test case for create_crypto_address

        Create crypto address
        """
        """
        create_crypto_address_request = cobo_waas2.CreateCryptoAddressRequest()

        api_response = self.api.create_crypto_address(create_crypto_address_request=create_crypto_address_request)
        """

    def test_create_destination(self) -> None:
        """
        Test case for create_destination

        Create destination
        """
        """
        create_destination_request = cobo_waas2.CreateDestinationRequest()

        api_response = self.api.create_destination(create_destination_request=create_destination_request)
        """

    def test_create_destination_entry(self) -> None:
        """
        Test case for create_destination_entry

        Create destination entry
        """
        """
        create_destination_entry_request = cobo_waas2.CreateDestinationEntryRequest()

        api_response = self.api.create_destination_entry(create_destination_entry_request=create_destination_entry_request)
        """

    def test_create_forced_sweep_request(self) -> None:
        """
        Test case for create_forced_sweep_request

        Create forced sweep
        """
        """
        forced_sweep_request = cobo_waas2.ForcedSweepRequest()

        api_response = self.api.create_forced_sweep_request(forced_sweep_request=forced_sweep_request)
        """

    def test_create_merchant(self) -> None:
        """
        Test case for create_merchant

        Create merchant
        """
        """
        create_merchant_request = cobo_waas2.CreateMerchantRequest()

        api_response = self.api.create_merchant(create_merchant_request=create_merchant_request)
        """

    def test_create_order_link(self) -> None:
        """
        Test case for create_order_link

        Create order link
        """
        """
        create_order_link_request = cobo_waas2.CreateOrderLinkRequest()

        api_response = self.api.create_order_link(create_order_link_request=create_order_link_request)
        """

    def test_create_payment_order(self) -> None:
        """
        Test case for create_payment_order

        Create pay-in order
        """
        """
        create_payment_order_request = cobo_waas2.CreatePaymentOrderRequest()

        api_response = self.api.create_payment_order(create_payment_order_request=create_payment_order_request)
        """

    def test_create_payout(self) -> None:
        """
        Test case for create_payout

        Create payout
        """
        """
        create_payout_request = cobo_waas2.CreatePayoutRequest()

        api_response = self.api.create_payout(create_payout_request=create_payout_request)
        """

    def test_create_refund(self) -> None:
        """
        Test case for create_refund

        Create refund order
        """
        """
        create_refund_request = cobo_waas2.CreateRefundRequest()

        api_response = self.api.create_refund(create_refund_request=create_refund_request)
        """

    def test_create_refund_link(self) -> None:
        """
        Test case for create_refund_link

        Create refund link
        """
        """
        create_refund_link_request = cobo_waas2.CreateRefundLinkRequest()

        api_response = self.api.create_refund_link(create_refund_link_request=create_refund_link_request)
        """

    def test_create_report(self) -> None:
        """
        Test case for create_report

        Generate reports
        """
        """
        create_report_request = cobo_waas2.CreateReportRequest()

        api_response = self.api.create_report(create_report_request=create_report_request)
        """

    def test_create_sdk_link(self) -> None:
        """
        Test case for create_sdk_link

        Create SDK link
        """
        """

        api_response = self.api.create_sdk_link()
        """

    def test_create_settlement_request(self) -> None:
        """
        Test case for create_settlement_request

        Create settlement request
        """
        """
        create_settlement_request_request = cobo_waas2.CreateSettlementRequestRequest()

        api_response = self.api.create_settlement_request(create_settlement_request_request=create_settlement_request_request)
        """

    def test_create_top_up_addresses(self) -> None:
        """
        Test case for create_top_up_addresses

        Batch create top-up addresses
        """
        """
        create_top_up_addresses = cobo_waas2.CreateTopUpAddresses()

        api_response = self.api.create_top_up_addresses(create_top_up_addresses=create_top_up_addresses)
        """

    def test_delete_counterparty_by_id(self) -> None:
        """
        Test case for delete_counterparty_by_id

        Delete counterparty
        """
        """
        counterparty_id = '5b0ed293-f728-40b4-b1f6-86b88cd51384'

        api_response = self.api.delete_counterparty_by_id(counterparty_id)
        """

    def test_delete_counterparty_entry(self) -> None:
        """
        Test case for delete_counterparty_entry

        Delete counterparty entry
        """
        """
        counterparty_entry_id = '123e4567-e89b-12d3-a456-426614174003'
        counterparty_id = '5b0ed293-f728-40b4-b1f6-86b88cd51384'
        entry_type = cobo_waas2.EntryType()

        api_response = self.api.delete_counterparty_entry(counterparty_entry_id, counterparty_id, entry_type=entry_type)
        """

    def test_delete_crypto_address(self) -> None:
        """
        Test case for delete_crypto_address

        Delete crypto address
        """
        """
        crypto_address_id = 'addr_ethusdt_20250506T123456_ab12cd'

        api_response = self.api.delete_crypto_address(crypto_address_id)
        """

    def test_delete_destination_by_id(self) -> None:
        """
        Test case for delete_destination_by_id

        Delete destination
        """
        """
        destination_id = '46beeab4-6a8e-476e-bc69-99b89aacbc6f'

        api_response = self.api.delete_destination_by_id(destination_id)
        """

    def test_delete_destination_entry(self) -> None:
        """
        Test case for delete_destination_entry

        Delete destination entry
        """
        """
        destination_entry_id = '123e4567-e89b-12d3-a456-426614174003'
        destination_id = '46beeab4-6a8e-476e-bc69-99b89aacbc6f'
        entry_type = cobo_waas2.EntryType()

        api_response = self.api.delete_destination_entry(destination_entry_id, destination_id, entry_type)
        """

    def test_get_available_allocation_amount(self) -> None:
        """
        Test case for get_available_allocation_amount

        Get available allocation amount
        """
        """
        token_id = 'ETH_USDT'
        source_account = 'source_account_example'
        destination_account = 'destination_account_example'

        api_response = self.api.get_available_allocation_amount(token_id, source_account, destination_account)
        """

    def test_get_batch_allocation_by_id(self) -> None:
        """
        Test case for get_batch_allocation_by_id

        Get batch allocation information
        """
        """
        batch_allocation_id = '5b0ed293-f728-40b4-b1f6-86b88cd51384'

        api_response = self.api.get_batch_allocation_by_id(batch_allocation_id)
        """

    def test_get_bulk_send_by_id(self) -> None:
        """
        Test case for get_bulk_send_by_id

        Get bulk send information
        """
        """
        bulk_send_id = '123e4567-e89b-12d3-a456-426614174003'

        api_response = self.api.get_bulk_send_by_id(bulk_send_id)
        """

    def test_get_counterparty(self) -> None:
        """
        Test case for get_counterparty

        Get counterparty information
        """
        """
        counterparty_id = '5b0ed293-f728-40b4-b1f6-86b88cd51384'

        api_response = self.api.get_counterparty(counterparty_id)
        """

    def test_get_counterparty_entry(self) -> None:
        """
        Test case for get_counterparty_entry

        Get counterparty entry information
        """
        """
        counterparty_entry_id = '123e4567-e89b-12d3-a456-426614174003'
        entry_type = cobo_waas2.EntryType()

        api_response = self.api.get_counterparty_entry(counterparty_entry_id, entry_type=entry_type)
        """

    def test_get_destination(self) -> None:
        """
        Test case for get_destination

        Get destination information
        """
        """
        destination_id = '46beeab4-6a8e-476e-bc69-99b89aacbc6f'

        api_response = self.api.get_destination(destination_id)
        """

    def test_get_destination_entry(self) -> None:
        """
        Test case for get_destination_entry

        Get destination entry information
        """
        """
        destination_entry_id = '123e4567-e89b-12d3-a456-426614174003'
        entry_type = cobo_waas2.EntryType()

        api_response = self.api.get_destination_entry(destination_entry_id, entry_type)
        """

    def test_get_exchange_rate(self) -> None:
        """
        Test case for get_exchange_rate

        Get exchange rate
        """
        """
        token_id = 'ETH_USDT'
        currency = 'USD'

        api_response = self.api.get_exchange_rate(token_id, currency)
        """

    def test_get_payment_order_detail_by_id(self) -> None:
        """
        Test case for get_payment_order_detail_by_id

        Get pay-in order information
        """
        """
        order_id = 'O20250304-M1001-1001'

        api_response = self.api.get_payment_order_detail_by_id(order_id)
        """

    def test_get_payout_by_id(self) -> None:
        """
        Test case for get_payout_by_id

        Get payout information
        """
        """
        payout_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f'

        api_response = self.api.get_payout_by_id(payout_id)
        """

    def test_get_psp_balance(self) -> None:
        """
        Test case for get_psp_balance

        Get developer balance
        """
        """
        token_id = 'ETH_USDT'

        api_response = self.api.get_psp_balance(token_id)
        """

    def test_get_refund_detail_by_id(self) -> None:
        """
        Test case for get_refund_detail_by_id

        Get refund order information
        """
        """
        refund_id = 'R20250304-M1001-1001'

        api_response = self.api.get_refund_detail_by_id(refund_id)
        """

    def test_get_refunds(self) -> None:
        """
        Test case for get_refunds

        List all refund orders
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        merchant_id = 'M1001'
        request_id = 'random_request_id'
        statuses = 'Pending,Processing'

        api_response = self.api.get_refunds(limit=limit, before=before, after=after, merchant_id=merchant_id, request_id=request_id, statuses=statuses)
        """

    def test_get_reports(self) -> None:
        """
        Test case for get_reports

        List all reports
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        report_type = cobo_waas2.ReportType()
        report_status = cobo_waas2.ReportStatus()

        api_response = self.api.get_reports(limit=limit, before=before, after=after, report_type=report_type, report_status=report_status)
        """

    def test_get_settlement_by_id(self) -> None:
        """
        Test case for get_settlement_by_id

        Get settlement request information
        """
        """
        settlement_request_id = 'S20250304-1001'

        api_response = self.api.get_settlement_by_id(settlement_request_id)
        """

    def test_get_settlement_info_by_ids(self) -> None:
        """
        Test case for get_settlement_info_by_ids

        Get withdrawable balances
        """
        """
        merchant_ids = 'M1001,M1002,M1003'
        currency = 'USD'
        acquiring_type = cobo_waas2.AcquiringType()

        api_response = self.api.get_settlement_info_by_ids(merchant_ids=merchant_ids, currency=currency, acquiring_type=acquiring_type)
        """

    def test_get_top_up_address(self) -> None:
        """
        Test case for get_top_up_address

        Create/Get top-up address
        """
        """
        token_id = 'ETH_USDT'
        custom_payer_id = 'payer_0001'
        merchant_id = 'M1001'

        api_response = self.api.get_top_up_address(token_id, custom_payer_id, merchant_id=merchant_id)
        """

    def test_list_allocation_items(self) -> None:
        """
        Test case for list_allocation_items

        List all allocation items
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        source_account = 'source_account_example'
        destination_account = 'destination_account_example'
        token_id = 'ETH_USDT'
        batch_allocation_id = '5b0ed293-f728-40b4-b1f6-86b88cd51384'

        api_response = self.api.list_allocation_items(limit=limit, before=before, after=after, source_account=source_account, destination_account=destination_account, token_id=token_id, batch_allocation_id=batch_allocation_id)
        """

    def test_list_bank_accounts(self) -> None:
        """
        Test case for list_bank_accounts

        List all bank accounts
        """
        """

        api_response = self.api.list_bank_accounts()
        """

    def test_list_batch_allocations(self) -> None:
        """
        Test case for list_batch_allocations

        List all batch allocations
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        request_id = 'random_request_id'

        api_response = self.api.list_batch_allocations(limit=limit, before=before, after=after, request_id=request_id)
        """

    def test_list_bulk_send_items(self) -> None:
        """
        Test case for list_bulk_send_items

        List bulk send items
        """
        """
        bulk_send_id = '123e4567-e89b-12d3-a456-426614174003'
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'

        api_response = self.api.list_bulk_send_items(bulk_send_id, limit=limit, before=before, after=after)
        """

    def test_list_counterparties(self) -> None:
        """
        Test case for list_counterparties

        List all counterparties
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        keyword = 'keyword'
        counterparty_type = cobo_waas2.CounterpartyType()
        country = 'USA'

        api_response = self.api.list_counterparties(limit=limit, before=before, after=after, keyword=keyword, counterparty_type=counterparty_type, country=country)
        """

    def test_list_counterparty_entries(self) -> None:
        """
        Test case for list_counterparty_entries

        List counterparty entries
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        entry_type = cobo_waas2.EntryType()
        counterparty_id = '5b0ed293-f728-40b4-b1f6-86b88cd51384'
        chain_ids = 'ETH'
        wallet_address = '0x1234567890abcdef...'

        api_response = self.api.list_counterparty_entries(limit=limit, before=before, after=after, entry_type=entry_type, counterparty_id=counterparty_id, chain_ids=chain_ids, wallet_address=wallet_address)
        """

    def test_list_crypto_addresses(self) -> None:
        """
        Test case for list_crypto_addresses

        List crypto addresses
        """
        """
        token_id = 'ETH_USDT'

        api_response = self.api.list_crypto_addresses(token_id=token_id)
        """

    def test_list_destination_entries(self) -> None:
        """
        Test case for list_destination_entries

        List destination entries
        """
        """
        entry_type = cobo_waas2.EntryType()
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        destination_id = '46beeab4-6a8e-476e-bc69-99b89aacbc6f'
        chain_ids = 'ETH'
        wallet_address = '0x1234567890abcdef...'
        keyword = 'keyword'
        bank_account_status = cobo_waas2.BankAccountStatus()

        api_response = self.api.list_destination_entries(entry_type, limit=limit, before=before, after=after, destination_id=destination_id, chain_ids=chain_ids, wallet_address=wallet_address, keyword=keyword, bank_account_status=bank_account_status)
        """

    def test_list_destinations(self) -> None:
        """
        Test case for list_destinations

        List all destinations
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        keyword = 'keyword'
        destination_type = cobo_waas2.DestinationType()
        country = 'USA'
        merchant_ids = 'M1001,M1002,M1003'

        api_response = self.api.list_destinations(limit=limit, before=before, after=after, keyword=keyword, destination_type=destination_type, country=country, merchant_ids=merchant_ids)
        """

    def test_list_forced_sweep_requests(self) -> None:
        """
        Test case for list_forced_sweep_requests

        List forced sweeps
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        request_id = 'random_request_id'

        api_response = self.api.list_forced_sweep_requests(limit=limit, before=before, after=after, request_id=request_id)
        """

    def test_list_merchant_balances(self) -> None:
        """
        Test case for list_merchant_balances

        List merchant balances
        """
        """
        merchant_ids = 'M1001,M1002,M1003'
        token_id = 'ETH_USDT'
        acquiring_type = cobo_waas2.AcquiringType()

        api_response = self.api.list_merchant_balances(merchant_ids=merchant_ids, token_id=token_id, acquiring_type=acquiring_type)
        """

    def test_list_merchants(self) -> None:
        """
        Test case for list_merchants

        List all merchants
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        keyword = 'keyword'
        wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479'
        wallet_setup = cobo_waas2.WalletSetup()

        api_response = self.api.list_merchants(limit=limit, before=before, after=after, keyword=keyword, wallet_id=wallet_id, wallet_setup=wallet_setup)
        """

    def test_list_payment_orders(self) -> None:
        """
        Test case for list_payment_orders

        List all pay-in orders
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        merchant_id = 'M1001'
        psp_order_id = 'P20240201001'
        statuses = 'Pending,Processing'

        api_response = self.api.list_payment_orders(limit=limit, before=before, after=after, merchant_id=merchant_id, psp_order_id=psp_order_id, statuses=statuses)
        """

    def test_list_payment_supported_tokens(self) -> None:
        """
        Test case for list_payment_supported_tokens

        List supported tokens
        """
        """

        api_response = self.api.list_payment_supported_tokens()
        """

    def test_list_payment_wallet_balances(self) -> None:
        """
        Test case for list_payment_wallet_balances

        List payment wallet balances
        """
        """
        token_id = 'ETH_USDT'
        wallet_ids = 'f47ac10b-58cc-4372-a567-0e02b2c3d479,f47ac10b-58cc-4372-a567-0e02b2c3d472'

        api_response = self.api.list_payment_wallet_balances(token_id, wallet_ids=wallet_ids)
        """

    def test_list_payouts(self) -> None:
        """
        Test case for list_payouts

        List all payouts
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        request_id = 'random_request_id'

        api_response = self.api.list_payouts(limit=limit, before=before, after=after, request_id=request_id)
        """

    def test_list_settlement_details(self) -> None:
        """
        Test case for list_settlement_details

        List all settlement details
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        merchant_id = 'M1001'
        statuses = 'Pending,Processing'

        api_response = self.api.list_settlement_details(limit=limit, before=before, after=after, merchant_id=merchant_id, statuses=statuses)
        """

    def test_list_settlement_requests(self) -> None:
        """
        Test case for list_settlement_requests

        List all settlement requests
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        request_id = 'random_request_id'

        api_response = self.api.list_settlement_requests(limit=limit, before=before, after=after, request_id=request_id)
        """

    def test_list_top_up_payer_accounts(self) -> None:
        """
        Test case for list_top_up_payer_accounts

        List top-up payer accounts
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        merchant_id = 'M1001'
        payer_id = 'P20250619T0310056d7aa'

        api_response = self.api.list_top_up_payer_accounts(limit=limit, before=before, after=after, merchant_id=merchant_id, payer_id=payer_id)
        """

    def test_list_top_up_payers(self) -> None:
        """
        Test case for list_top_up_payers

        List payers
        """
        """
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        merchant_id = 'M1001'
        payer_id = 'P20250619T0310056d7aa'

        api_response = self.api.list_top_up_payers(limit=limit, before=before, after=after, merchant_id=merchant_id, payer_id=payer_id)
        """

    def test_payment_estimate_fee(self) -> None:
        """
        Test case for payment_estimate_fee

        Estimate fees
        """
        """
        payment_estimate_fee_request = cobo_waas2.PaymentEstimateFeeRequest()

        api_response = self.api.payment_estimate_fee(payment_estimate_fee_request=payment_estimate_fee_request)
        """

    def test_trigger_test_payments_webhook_event(self) -> None:
        """
        Test case for trigger_test_payments_webhook_event

        Trigger test webhook event
        """
        """
        trigger_test_payments_webhook_event_request = cobo_waas2.TriggerTestPaymentsWebhookEventRequest()

        api_response = self.api.trigger_test_payments_webhook_event(trigger_test_payments_webhook_event_request=trigger_test_payments_webhook_event_request)
        """

    def test_update_bank_account_by_id(self) -> None:
        """
        Test case for update_bank_account_by_id

        Update bank account
        """
        """
        bank_account_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479'
        update_bank_account_by_id_request = cobo_waas2.UpdateBankAccountByIdRequest()

        api_response = self.api.update_bank_account_by_id(bank_account_id, update_bank_account_by_id_request=update_bank_account_by_id_request)
        """

    def test_update_counterparty(self) -> None:
        """
        Test case for update_counterparty

        Update counterparty
        """
        """
        counterparty_id = '5b0ed293-f728-40b4-b1f6-86b88cd51384'
        update_counterparty_request = cobo_waas2.UpdateCounterpartyRequest()

        api_response = self.api.update_counterparty(counterparty_id, update_counterparty_request=update_counterparty_request)
        """

    def test_update_destination(self) -> None:
        """
        Test case for update_destination

        Update destination
        """
        """
        destination_id = '46beeab4-6a8e-476e-bc69-99b89aacbc6f'
        update_destination_request = cobo_waas2.UpdateDestinationRequest()

        api_response = self.api.update_destination(destination_id, update_destination_request=update_destination_request)
        """

    def test_update_destination_entry(self) -> None:
        """
        Test case for update_destination_entry

        Update destination entry
        """
        """
        destination_entry_id = '123e4567-e89b-12d3-a456-426614174003'
        update_destination_entry_request = cobo_waas2.UpdateDestinationEntryRequest()

        api_response = self.api.update_destination_entry(destination_entry_id, update_destination_entry_request=update_destination_entry_request)
        """

    def test_update_merchant_by_id(self) -> None:
        """
        Test case for update_merchant_by_id

        Update merchant
        """
        """
        merchant_id = 'M1001'
        update_merchant_by_id_request = cobo_waas2.UpdateMerchantByIdRequest()

        api_response = self.api.update_merchant_by_id(merchant_id, update_merchant_by_id_request=update_merchant_by_id_request)
        """

    def test_update_payment_order(self) -> None:
        """
        Test case for update_payment_order

        Update pay-in order
        """
        """
        order_id = 'O20250304-M1001-1001'
        update_payment_order_request = cobo_waas2.UpdatePaymentOrderRequest()

        api_response = self.api.update_payment_order(order_id, update_payment_order_request=update_payment_order_request)
        """

    def test_update_refund_by_id(self) -> None:
        """
        Test case for update_refund_by_id

        Update refund order
        """
        """
        refund_id = 'R20250304-M1001-1001'
        update_refund_by_id_request = cobo_waas2.UpdateRefundByIdRequest()

        api_response = self.api.update_refund_by_id(refund_id, update_refund_by_id_request=update_refund_by_id_request)
        """

    def test_update_top_up_address(self) -> None:
        """
        Test case for update_top_up_address

        Update top-up address
        """
        """
        update_top_up_address = cobo_waas2.UpdateTopUpAddress()

        api_response = self.api.update_top_up_address(update_top_up_address=update_top_up_address)
        """


if __name__ == '__main__':
    unittest.main()
