# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2 import Configuration
from cobo_waas2.api.auto_sweep_api import AutoSweepApi


class TestAutoSweepApi(unittest.TestCase):
    """AutoSweepApi unit test stubs"""

    def setUp(self) -> None:
        Configuration.set_default(Configuration(
            api_private_key="c203fccc02a2269ec486d9c32ff74b5ba6ab0cdb461ee1fb0dfc616109115c06",
            host="https://api.sandbox.cobo.com/v2"
        ))
        self.api = AutoSweepApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_auto_sweep_task_by_id(self) -> None:
        """
        Test case for cancel_auto_sweep_task_by_id

        Cancel auto sweep task
        """
        """
        task_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479'

        api_response = self.api.cancel_auto_sweep_task_by_id(task_id)
        """

    def test_create_auto_sweep_task(self) -> None:
        """
        Test case for create_auto_sweep_task

        Create auto-sweep task
        """
        """
        create_auto_sweep_task = cobo_waas2.CreateAutoSweepTask()

        api_response = self.api.create_auto_sweep_task(create_auto_sweep_task=create_auto_sweep_task)
        """

    def test_create_wallet_sweep_to_addresses(self) -> None:
        """
        Test case for create_wallet_sweep_to_addresses

        Create sweep-to address
        """
        """
        create_sweep_to_address = cobo_waas2.CreateSweepToAddress()

        api_response = self.api.create_wallet_sweep_to_addresses(create_sweep_to_address=create_sweep_to_address)
        """

    def test_get_auto_sweep_task_by_id(self) -> None:
        """
        Test case for get_auto_sweep_task_by_id

        Get auto-sweep task details
        """
        """
        task_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479'

        api_response = self.api.get_auto_sweep_task_by_id(task_id)
        """

    def test_list_auto_sweep_task(self) -> None:
        """
        Test case for list_auto_sweep_task

        List auto-sweep tasks
        """
        """
        wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479'
        token_id = 'ETH_USDT'
        task_ids = 'f47ac10b-58cc-4372-a567-0e02b2c3d479,1ddca562-8434-41c9-8809-d437bad9c868'
        min_created_timestamp = 1635744000000
        max_created_timestamp = 1635744000000
        limit = 10
        before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1'
        after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk'
        direction = 'ASC'

        api_response = self.api.list_auto_sweep_task(wallet_id, token_id=token_id, task_ids=task_ids, min_created_timestamp=min_created_timestamp, max_created_timestamp=max_created_timestamp, limit=limit, before=before, after=after, direction=direction)
        """

    def test_list_wallet_sweep_to_addresses(self) -> None:
        """
        Test case for list_wallet_sweep_to_addresses

        List sweep-to addresses
        """
        """
        wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479'

        api_response = self.api.list_wallet_sweep_to_addresses(wallet_id)
        """


if __name__ == '__main__':
    unittest.main()
