# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.fee_station_fiat_transaction_type import FeeStationFiatTransactionType


class TestFeeStationFiatTransactionType(unittest.TestCase):
    """FeeStationFiatTransactionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeeStationFiatTransactionType(self):
        """Test FeeStationFiatTransactionType"""
        # inst = FeeStationFiatTransactionType()


if __name__ == '__main__':
    unittest.main()
