# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.list_fee_station_fiat_transactions200_response import ListFeeStationFiatTransactions200Response


class TestListFeeStationFiatTransactions200Response(unittest.TestCase):
    """ListFeeStationFiatTransactions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListFeeStationFiatTransactions200Response:
        """Test ListFeeStationFiatTransactions200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListFeeStationFiatTransactions200Response`
        """
        model = ListFeeStationFiatTransactions200Response()
        if include_optional:
            return ListFeeStationFiatTransactions200Response(
                data = [
                    cobo_waas2.models.fee_station_fiat_transaction.FeeStationFiatTransaction(
                        transaction_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479', 
                        main_transaction_id = 'b0530b27-104f-4338-87de-de01500326ea', 
                        transaction_type = 'deposit', 
                        amount = '100.00', 
                        fiat_currency = 'USD', 
                        status = 'Succeeded', 
                        cobo_category = ["GasFeeSponsor"], 
                        created_timestamp = 1635744000000, 
                        modified_timestamp = 1635744000000, )
                    ],
                pagination = cobo_waas2.models.pagination.Pagination(
                    before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1', 
                    after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk', 
                    total_count = 10000, )
            )
        else:
            return ListFeeStationFiatTransactions200Response(
        )
        """

    def testListFeeStationFiatTransactions200Response(self):
        """Test ListFeeStationFiatTransactions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
