# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.refund_link_business_info import RefundLinkBusinessInfo


class TestRefundLinkBusinessInfo(unittest.TestCase):
    """RefundLinkBusinessInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefundLinkBusinessInfo:
        """Test RefundLinkBusinessInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefundLinkBusinessInfo`
        """
        model = RefundLinkBusinessInfo()
        if include_optional:
            return RefundLinkBusinessInfo(
                order_id = 'O20250304-M1001-1001',
                transaction_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f',
                amount = '0.0025',
                refund_source = 'Merchant',
                merchant_id = 'M1001',
                fee_amount = '0.0001'
            )
        else:
            return RefundLinkBusinessInfo(
                amount = '0.0025',
                refund_source = 'Merchant',
        )
        """

    def testRefundLinkBusinessInfo(self):
        """Test RefundLinkBusinessInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
