# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cobo_waas2.models.fee_station_fiat_transaction_type import FeeStationFiatTransactionType
from typing import Optional, Set
from typing_extensions import Self


class FeeStationFiatTransaction(BaseModel):
    """
    The information about a fiat transaction.
    """  # noqa: E501
    transaction_id: StrictStr = Field(description="The transaction ID.")
    main_transaction_id: Optional[StrictStr] = Field(default=None, description="The UUID of the parent (main) transaction that this record is associated with. Set only when the current record is a gas/fee transaction initiated by FeeStation; omit for main transactions.")
    transaction_type: FeeStationFiatTransactionType
    amount: StrictStr = Field(description="The transaction amount.")
    fiat_currency: StrictStr = Field(description="The fiat currency of the transaction. Possible values include:   - `USD`: US Dollar. ")
    status: StrictStr = Field(description="The status of the fiat transaction. Possible values include:   - `Created`: The transaction has been created.   - `Succeeded`: The transaction has been completed successfully. ")
    cobo_category: Optional[List[StrictStr]] = Field(default=None, description="The Cobo category of the transaction.")
    created_timestamp: Optional[StrictInt] = Field(default=None, description="The time when the transaction was created, in Unix timestamp format, measured in milliseconds.")
    modified_timestamp: Optional[StrictInt] = Field(default=None, description="The time when the transaction was last modified, in Unix timestamp format, measured in milliseconds.")
    __properties: ClassVar[List[str]] = ["transaction_id", "main_transaction_id", "transaction_type", "amount", "fiat_currency", "status", "cobo_category", "created_timestamp", "modified_timestamp"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Created', 'Succeeded']):
            raise ValueError("must be one of enum values ('Created', 'Succeeded')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeeStationFiatTransaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeeStationFiatTransaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transaction_id": obj.get("transaction_id"),
            "main_transaction_id": obj.get("main_transaction_id"),
            "transaction_type": obj.get("transaction_type"),
            "amount": obj.get("amount"),
            "fiat_currency": obj.get("fiat_currency"),
            "status": obj.get("status"),
            "cobo_category": obj.get("cobo_category"),
            "created_timestamp": obj.get("created_timestamp"),
            "modified_timestamp": obj.get("modified_timestamp")
        })
        return _obj


